# Generated by Django 5.2.3 on 2025-09-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('pilar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_auditoria', to='auditorias.pilar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Categoria de Auditoria',
                'verbose_name_plural': 'Categorias de Auditorias',
                'ordering': ['pilar__nome', 'descricao'],
                'unique_together': {('pilar', 'descricao')},
            },
        ),
    ]
