# Generated by Django 5.2.3 on 2025-09-01 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_categoriaauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True, verbose_name='Descrição da Norma')),
                ('revisao', models.CharField(max_length=100, verbose_name='Revisão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'ordering': ['descricao', 'revisao'],
                'unique_together': {('descricao', 'revisao')},
            },
        ),
        migrations.CreateModel(
            name='RequisitoNorma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('requisito', models.CharField(max_length=255, verbose_name='Requisito')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('norma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='auditorias.norma', verbose_name='Norma')),
            ],
            options={
                'verbose_name': 'Requisito de Norma',
                'verbose_name_plural': 'Requisitos de Normas',
                'ordering': ['norma__descricao', 'codigo'],
                'unique_together': {('norma', 'codigo')},
            },
        ),
    ]
