# Generated by Django 5.2.3 on 2025-09-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_norma_requisitonorma'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerramentaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Ferramenta')),
            ],
            options={
                'verbose_name': 'Ferramenta Digital',
                'verbose_name_plural': 'Ferramentas Digitais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Questão')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_tipos_questao/', verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Tipo de Questão',
                'verbose_name_plural': 'Tipos de Questão',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo de Avaliação')),
                ('descricao', models.TextField(verbose_name='Descrição do Modelo')),
                ('tipos_questao_suportados', models.ManyToManyField(related_name='modelos_avaliacao', to='auditorias.tipoquestao', verbose_name='Tipos de Questão Suportados')),
            ],
            options={
                'verbose_name': 'Modelo de Avaliação',
                'verbose_name_plural': 'Modelos de Avaliação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Checklist')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ferramentas', models.ManyToManyField(related_name='checklists', to='auditorias.ferramentadigital', verbose_name='Ferramentas Digitais')),
                ('modelo_avaliacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='auditorias.modeloavaliacao', verbose_name='Modelo de Avaliação')),
                ('tipo_questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='auditorias.tipoquestao', verbose_name='Tipo de Questão')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['nome'],
            },
        ),
    ]
