# Generated by Django 5.2.3 on 2025-09-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0004_ferramentadigital_tipoquestao_modeloavaliacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='ferramentas',
        ),
        migrations.AddField(
            model_name='checklist',
            name='ferramenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='auditorias.ferramentadigital', verbose_name='Ferramenta Digital'),
        ),
    ]
