# Generated by Django 5.2.3 on 2025-09-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0005_remove_checklist_ferramentas_checklist_ferramenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FerramentaCausaRaiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Ferramenta')),
            ],
            options={
                'verbose_name': 'Ferramenta de Causa Raiz',
                'verbose_name_plural': 'Ferramentas de Causa Raiz',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModeloAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Modelo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('iniciar_por_codigo_qr', models.BooleanField(default=False, verbose_name='Iniciar por Código QR')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_auditoria', to='auditorias.categoriaauditoria', verbose_name='Categoria')),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_auditoria', to='auditorias.checklist', verbose_name='Checklist')),
                ('ferramenta_causa_raiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_auditoria', to='auditorias.ferramentacausaraiz', verbose_name='Ferramenta para Causa Raiz')),
            ],
            options={
                'verbose_name': 'Modelo de Auditoria',
                'verbose_name_plural': 'Modelos de Auditoria',
                'ordering': ['descricao'],
            },
        ),
    ]
