# Generated by Django 5.2.3 on 2025-09-01 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
        ('auditorias', '0006_ferramentacausaraiz_modeloauditoria'),
        ('organizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_organizacional', models.CharField(choices=[('EMPRESA', 'Empresa'), ('AREA', 'Área'), ('SETOR', 'Setor'), ('SUBSETOR', 'Subsetor')], max_length=50, verbose_name='Nível')),
                ('categoria_auditoria', models.CharField(choices=[('APP', 'App'), ('WEB', 'Web')], max_length=10, verbose_name='Categoria')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('por_frequencia', models.BooleanField(default=False, verbose_name='Por Frequência')),
                ('por_intervalo', models.BooleanField(default=False, verbose_name='Por Intervalo')),
                ('frequencia', models.CharField(blank=True, choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=10, null=True, verbose_name='Frequência')),
                ('intervalo', models.IntegerField(blank=True, null=True, verbose_name='Intervalo')),
                ('numero_repeticoes', models.IntegerField(blank=True, null=True, verbose_name='Número de Repetições')),
                ('pular_finais_semana', models.BooleanField(default=False, verbose_name='Pular Finais de Semana')),
                ('contem_turnos', models.BooleanField(default=False, verbose_name='Contém Turnos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativos_auditados', models.ManyToManyField(related_name='auditorias_agendadas', to='ativos.ativo', verbose_name='Ativos Auditados')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.ferramentadigital', verbose_name='Ferramenta Digital')),
                ('local_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.area', verbose_name='Local (Área)')),
                ('local_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.empresa', verbose_name='Local (Empresa)')),
                ('local_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.setor', verbose_name='Local (Setor)')),
                ('local_subsetor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.subsetor', verbose_name='Local (Subsetor)')),
                ('modelos', models.ManyToManyField(to='auditorias.modeloauditoria', verbose_name='Modelos de Auditoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Auditoria Agendada',
                'verbose_name_plural': 'Auditorias Agendadas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data de Execução')),
                ('executada', models.BooleanField(default=False, verbose_name='Executada?')),
                ('auditoria_agendada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='auditorias.auditoria', verbose_name='Auditoria Agendada')),
            ],
            options={
                'verbose_name': 'Instância de Auditoria',
                'verbose_name_plural': 'Instâncias de Auditoria',
                'ordering': ['data_execucao'],
            },
        ),
    ]
