# Generated by Django 5.2.3 on 2025-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0007_auditoria_auditoriainstancia'),
        ('cadastros_base', '0002_alter_turno_options_remove_turno_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='turnos',
            field=models.ManyToManyField(blank=True, to='cadastros_base.turno', verbose_name='Turnos'),
        ),
    ]
