# Generated by Django 5.2.4 on 2025-09-02 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0008_auditoria_turnos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='tipo_questao',
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Tópico')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='auditorias.checklist', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['ordem', 'descricao'],
                'unique_together': {('checklist', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Pergunta')),
                ('campo_obrigatorio', models.BooleanField(default=False, verbose_name='Campo Obrigatório')),
                ('campo_desabilitado', models.BooleanField(default=False, verbose_name='Campo Desabilitado')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem')),
                ('tipo_questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perguntas', to='auditorias.tipoquestao', verbose_name='Tipo de Questão')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='auditorias.topico', verbose_name='Tópico')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['ordem', 'descricao'],
                'unique_together': {('topico', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da Opção')),
                ('tipo_status', models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('DESVIO_SOLUCIONADO', 'Desvio Solucionado'), ('NA', 'N/A')], max_length=20, verbose_name='Tipo de Status')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='auditorias.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Pergunta',
                'verbose_name_plural': 'Opções de Perguntas',
                'unique_together': {('pergunta', 'descricao')},
            },
        ),
    ]
