# Generated by Django 5.2.4 on 2025-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0009_remove_checklist_tipo_questao_topico_pergunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcaopergunta',
            name='instrucoes_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções do Usuário'),
        ),
        migrations.AlterField(
            model_name='opcaopergunta',
            name='tipo_status',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NA', 'N/A'), ('DESVIO_SOLUCIONADO', 'Desvio Solucionado')], max_length=20, verbose_name='Tipo de Status'),
        ),
    ]
