# Generated by Django 5.2.6 on 2025-09-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0010_opcaopergunta_instrucoes_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='modelo_avaliacao',
        ),
        migrations.AlterUniqueTogether(
            name='opcaopergunta',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='opcaopergunta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo_questao',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='criar_opcao',
            field=models.BooleanField(default=True, verbose_name='Permitir Criar uma Opção'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='foto',
            field=models.BooleanField(default=False, verbose_name='Permitir Foto'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='obrigatoria',
            field=models.BooleanField(default=False, verbose_name='Resposta Obrigatória'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='porcentagem',
            field=models.BooleanField(default=False, verbose_name='Permitir Porcentagem'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_livre',
            field=models.BooleanField(default=False, verbose_name='Permitir Resposta Livre'),
        ),
        migrations.CreateModel(
            name='OpcaoPorcentagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('peso', models.PositiveIntegerField(verbose_name='Peso (%)')),
                ('cor', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_porcentagem', to='auditorias.pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Porcentagem',
                'verbose_name_plural': 'Opções de Porcentagem',
                'ordering': ['peso'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Opção')),
                ('status', models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('DESVIO_SOLUCIONADO', 'Desvio Solucionado'), ('NA', 'N/A')], max_length=20, verbose_name='Status Vinculado')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_resposta', to='auditorias.pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Resposta',
                'verbose_name_plural': 'Opções de Resposta',
                'ordering': ['descricao'],
            },
        ),
        migrations.DeleteModel(
            name='ModeloAvaliacao',
        ),
        migrations.DeleteModel(
            name='OpcaoPergunta',
        ),
        migrations.DeleteModel(
            name='TipoQuestao',
        ),
    ]
