# Generated by Django 5.2.3 on 2025-10-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0011_remove_checklist_modelo_avaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_livre_texto', models.TextField(blank=True, null=True, verbose_name='Texto da Resposta Livre')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('auditoria_instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='auditorias.auditoriainstancia', verbose_name='Instância da Auditoria')),
                ('opcao_porcentagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.opcaoporcentagem', verbose_name='Opção de Porcentagem Selecionada')),
                ('opcao_resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.opcaoresposta', verbose_name='Opção de Resposta Selecionada')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='auditorias.pergunta', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('auditoria_instancia', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='AnexoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_respostas/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='auditorias.resposta', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Anexo da Resposta',
                'verbose_name_plural': 'Anexos das Respostas',
            },
        ),
    ]
