# Generated by Django 5.2.3 on 2025-10-08 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0013_auditoria_criado_por'),
        ('organizacao', '0002_area_usuario_responsavel_empresa_usuario_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainstancia',
            name='ocal_execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.subsetor', verbose_name='Local de Execução (Subsetor)'),
        ),
    ]
