# Generated by Django 5.2.3 on 2025-10-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0014_auditoriainstancia_ocal_execucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoriainstancia',
            old_name='ocal_execucao',
            new_name='local_execucao',
        ),
    ]
