# Generated by Django 5.2.3 on 2025-10-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0016_auditoriainstancia_responsavel'),
        ('cadastros_base', '0002_alter_turno_options_remove_turno_hora_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainstancia',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros_base.turno', verbose_name='Turno de Execução'),
        ),
    ]
