# Generated by Django 5.2.3 on 2025-10-13 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0017_auditoriainstancia_turno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['nome', '-versao'], 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.AddField(
            model_name='auditoriainstancia',
            name='checklist_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.checklist', verbose_name='Checklist Utilizado'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='checklist_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes_filhas', to='auditorias.checklist', verbose_name='Checklist de Origem'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_active_version',
            field=models.BooleanField(default=True, verbose_name='É a versão ativa?'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='versao',
            field=models.IntegerField(default=1, verbose_name='Versão'),
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together={('nome', 'is_active_version')},
        ),
    ]
