# Generated by Django 5.2.3 on 2025-10-13 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0018_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='checklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='checklist_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits_by_original', to='auditorias.checklist', verbose_name='Checklist Lógico'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='É a versão mais recente'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='original_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='auditorias.checklist', verbose_name='Checklist Original'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão'),
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='checklist_pai',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='is_active_version',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='versao',
        ),
    ]
