# Generated by Django 5.2.3 on 2025-10-13 17:19

from django.db import migrations


def fix_latest_checklists(apps, schema_editor):
    """
    Para cada grupo de checklists com o mesmo nome, encontra o mais recente
    (baseado no campo 'version') e marca todos os outros como is_latest=False.
    """
    Checklist = apps.get_model('auditorias', 'Checklist')

    # Pega todos os nomes únicos de checklists
    unique_names = Checklist.objects.values('nome').distinct()

    for item in unique_names:
        nome = item['nome']
        # Pega todos os checklists com o mesmo nome, ordenando pela versão mais alta primeiro
        checklists_with_same_name = Checklist.objects.filter(
            nome=nome).order_by('-version')

        if checklists_with_same_name.exists():
            # O primeiro da lista é o mais recente, então o mantemos como 'is_latest=True'
            latest_checklist = checklists_with_same_name.first()

            # Todos os outros (excluindo o mais recente) devem ter 'is_latest' como False
            checklists_with_same_name.exclude(
                pk=latest_checklist.pk).update(is_latest=False)


class Migration(migrations.Migration):

    dependencies = [
        # Coloque aqui o nome da sua migração anterior (a que deu certo)
        ('auditorias', '0019_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_latest_checklists),
    ]
