# Generated by Django 5.2.3 on 2025-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0020_auto_20251013_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
    ]
