# Generated by Django 5.2.3 on 2025-10-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0021_alter_checklist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['nome'], 'verbose_name': 'Checklist', 'verbose_name_plural': 'Checklists'},
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='checklist_original',
        ),
        migrations.RemoveField(
            model_name='auditoriainstancia',
            name='checklist_usado',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='is_latest',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='original_checklist',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='version',
        ),
    ]
