# Generated by Django 5.2.3 on 2025-10-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0022_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriainstancia',
            name='checklist_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auditorias.checklist', verbose_name='Checklist Utilizado'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='É a versão mais recente'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='original_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='auditorias.checklist', verbose_name='Checklist Original'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versão'),
        ),
    ]
