# Generated by Django 5.2.3 on 2025-10-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0023_auditoriainstancia_checklist_usado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opcaoporcentagem',
            options={'ordering': ['ordem', 'peso'], 'verbose_name': 'Opção de Porcentagem', 'verbose_name_plural': 'Opções de Porcentagem'},
        ),
        migrations.AlterModelOptions(
            name='opcaoresposta',
            options={'ordering': ['ordem', 'descricao'], 'verbose_name': 'Opção de Resposta', 'verbose_name_plural': 'Opções de Resposta'},
        ),
        migrations.AddField(
            model_name='opcaoporcentagem',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AddField(
            model_name='opcaoresposta',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
