# Generated by Django 5.2.3 on 2025-10-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0024_alter_opcaoporcentagem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='desvio_solucionado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Desvio Solucionado na Hora'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='grau_nc',
            field=models.CharField(blank=True, choices=[('NC MAIOR', 'NC Maior'), ('NC MENOR', 'NC Menor')], max_length=20, null=True, verbose_name='Grau da Não Conformidade'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='oportunidade_melhoria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oportunidade de Melhoria'),
        ),
    ]
