# Generated by Django 5.2.3 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0025_resposta_desvio_solucionado_resposta_grau_nc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta'),
        ),
    ]
