# Generated by Django 5.2.3 on 2025-11-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0026_alter_resposta_data_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='descricao_desvio_nao_solucionado',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Desvio (Não Solucionado)'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='descricao_desvio_solucionado',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Desvio Solucionado'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='descricao_oportunidade_melhoria',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Oportunidade de Melhoria'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_livre_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da Resposta Livre (Observações)'),
        ),
    ]
