# Generated by Django 5.2.3 on 2025-11-04 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0027_resposta_descricao_desvio_nao_solucionado_and_more'),
        ('organizacao', '0002_area_usuario_responsavel_empresa_usuario_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NAO_CONFORMIDADE', 'Não Conformidade'), ('OPORTUNIDADE_MELHORIA', 'Oportunidade de Melhoria')], max_length=50, verbose_name='Tipo de Ação')),
                ('titulo', models.TextField(verbose_name='Título (Descrição da Pergunta)')),
                ('data_abertura', models.DateTimeField(verbose_name='Data da Ocorrência')),
                ('status_plano', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANALISE', 'Em Análise'), ('EM_IMPLEMENTACAO', 'Em Implementação'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=50, verbose_name='Status')),
                ('prazo_conclusao', models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('descricao_causa_raiz', models.TextField(blank=True, null=True, verbose_name='Descrição da Causa Raiz')),
                ('descricao_acao', models.TextField(blank=True, null=True, verbose_name='Descrição da Ação Corretiva/Melhoria')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.categoriaauditoria', verbose_name='Categoria da Auditoria')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.ferramentadigital', verbose_name='Ferramenta')),
                ('local_execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacao.subsetor', verbose_name='Local de Execução')),
                ('origem_resposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_de_acao', to='auditorias.resposta', verbose_name='Resposta de Origem')),
                ('responsavel_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_de_acao_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['-data_abertura'],
            },
        ),
    ]
