# Generated by Django 5.2.3 on 2025-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
        ('auditorias', '0028_planodeacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='agendamento_especifico',
            field=models.BooleanField(default=False, help_text='Se marcado, permite selecionar subsetores específicos. Se desmarcado, cria uma auditoria única para o nível selecionado (o local será escolhido no app).', verbose_name='Agendar para locais específicos'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='ativos_auditados',
            field=models.ManyToManyField(blank=True, related_name='auditorias_agendadas', to='ativos.ativo', verbose_name='Ativos Auditados'),
        ),
    ]
