# Generated by Django 5.2.3 on 2025-11-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0029_auditoria_agendamento_especifico_and_more'),
        ('planos_de_acao', '0002_alter_naoconformidade_data_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='forum',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plano_de_acao', to='planos_de_acao.forum', verbose_name='Fórum de Discussão'),
        ),
    ]
