# Generated by Django 5.2.3 on 2025-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0030_planodeacao_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeacao',
            name='status_plano',
            field=models.CharField(choices=[('ABERTO', 'Recebido'), ('EM_IMPLEMENTACAO', 'Em Implementação'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=50, verbose_name='Status'),
        ),
    ]
