# Generated by Django 5.2.3 on 2025-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0031_alter_planodeacao_status_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='motivo_arquivamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Arquivamento'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='status_plano',
            field=models.CharField(choices=[('ABERTO', 'Recebido'), ('EM_IMPLEMENTACAO', 'Em Implementação'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=50, verbose_name='Status'),
        ),
    ]
