# Generated by Django 5.2.3 on 2025-12-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0032_planodeacao_motivo_arquivamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='data_finalizacao_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data Finalização Prevista'),
        ),
    ]
