# Generated by Django 5.2.3 on 2025-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0033_planodeacao_data_finalizacao_prevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeacao',
            name='status_plano',
            field=models.CharField(choices=[('ABERTO', 'Recebido'), ('AGUARDANDO_VALIDACAO', 'Aguardando Validação'), ('EM_IMPLEMENTACAO', 'Em Implementação'), ('AGUARDANDO_APROVACAO', 'Aguardando Aprovação'), ('VALIDACAO_EFICACIA', 'Validação de Eficácia'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado'), ('ARQUIVADO', 'Arquivado')], default='ABERTO', max_length=50, verbose_name='Status'),
        ),
    ]
