# Generated by Django 5.2.3 on 2025-12-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0035_investimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='evidencias_planos/', verbose_name='Arquivo')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='auditorias.planodeacao', verbose_name='Plano de Ação')),
            ],
            options={
                'verbose_name': 'Evidência do Plano',
                'verbose_name_plural': 'Evidências do Plano',
            },
        ),
    ]
