# Generated by Django 5.2.3 on 2025-12-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0036_evidenciaplano'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='descricao_acao_realizada',
            field=models.TextField(blank=True, null=True, verbose_name='Ações Realizadas na Conclusão'),
        ),
    ]
