# Generated by Django 5.2.3 on 2025-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0037_planodeacao_descricao_acao_realizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='observacao_eficacia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da Eficácia'),
        ),
    ]
