# Generated by Django 5.2.3 on 2025-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0038_planodeacao_observacao_eficacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa/Devolução'),
        ),
    ]
