# Generated by Django 5.2.3 on 2025-12-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0039_planodeacao_motivo_recusa'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='orientacoes_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Orientações Adicionais (Clonagem)'),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='origem_resposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_acao', to='auditorias.resposta', verbose_name='Resposta de Origem'),
        ),
    ]
