# Generated by Django 5.2.3 on 2025-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0040_planodeacao_orientacoes_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='origem_orientacao',
            field=models.CharField(blank=True, choices=[('CLONAGEM', 'Clonagem'), ('REDIRECIONAMENTO', 'Redirecionamento')], max_length=20, null=True, verbose_name='Origem da Orientação'),
        ),
    ]
