# Generated by Django 5.2.3 on 2025-12-08 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0041_planodeacao_origem_orientacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Evento')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('STATUS', 'Mudança de Status'), ('EDICAO', 'Edição'), ('ANEXO', 'Anexo'), ('REDISTRIBUICAO', 'Redistribuição'), ('PRAZO', 'Alteração de Prazo')], default='STATUS', max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='auditorias.planodeacao', verbose_name='Plano de Ação')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
