# Generated by Django 5.2.3 on 2025-12-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0042_historicoplanoacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeacao',
            name='origem_resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_de_acao', to='auditorias.resposta', verbose_name='Resposta de Origem'),
        ),
    ]
