# Generated by Django 5.2.3 on 2025-12-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0043_alter_planodeacao_origem_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_manuais', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (Auditor Manual)'),
        ),
        migrations.AddField(
            model_name='planodeacao',
            name='observacao_origem',
            field=models.TextField(blank=True, null=True, verbose_name='Observação de Origem (Manual)'),
        ),
    ]
