# Generated by Django 5.2.3 on 2025-12-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0044_planodeacao_criado_por_planodeacao_observacao_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='planodeacao',
            name='fluxo_simplificado',
            field=models.BooleanField(default=False, verbose_name='Fluxo Simplificado (Sem Aprovações)'),
        ),
    ]
