# Generated by Django 6.0 on 2026-01-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0045_planodeacao_fluxo_simplificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaauditoria',
            name='dias_para_quarentena',
            field=models.PositiveIntegerField(default=7, help_text='Quantos dias de atraso são permitidos antes de entrar em quarentena.', verbose_name='Dias de Tolerância para Quarentena'),
        ),
    ]
