# Generated by Django 6.0 on 2026-01-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0046_categoriaauditoria_dias_para_quarentena'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='normas_relacionadas',
            field=models.ManyToManyField(blank=True, to='auditorias.norma', verbose_name='Normas Relacionadas'),
        ),
    ]
