# Generated by Django 6.0 on 2026-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0047_checklist_normas_relacionadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaoresposta',
            name='status',
            field=models.CharField(choices=[('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NA', 'N/A')], max_length=20, verbose_name='Status Vinculado'),
        ),
    ]
