# Generated by Django 6.0 on 2026-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0048_alter_opcaoresposta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramentadigital',
            name='aplicavel_em_checklist',
            field=models.BooleanField(default=True, verbose_name='É aplicável em checklists?'),
        ),
    ]
