# Generated by Django X.X on YYYY-MM-DD HH:MM

from django.db import migrations

# Nomes das ferramentas padrão que você deseja criar
FERRAMENTAS_PADRAO = [
    'E-5S',
    'E-Audit',
    'Plano de ação',
]


def criar_ferramentas_iniciais(apps, schema_editor):
    """
    Função que será executada pela migração para criar as ferramentas.
    """
    # Usamos apps.get_model para obter a versão histórica do modelo
    FerramentaDigital = apps.get_model('auditorias', 'FerramentaDigital')

    for nome_ferramenta in FERRAMENTAS_PADRAO:
        # get_or_create: cria a ferramenta se ela não existir.
        # Isso evita erros se a migração for executada mais de uma vez.
        FerramentaDigital.objects.get_or_create(nome=nome_ferramenta)


class Migration(migrations.Migration):

    dependencies = [
        # Coloque aqui o nome da sua última migração do app 'auditorias'
        # Ex: ('auditorias', '0001_initial'),
        ('auditorias', '0049_ferramentadigital_aplicavel_em_checklist'),
    ]

    operations = [
        # Esta linha diz ao Django para executar nossa função
        migrations.RunPython(criar_ferramentas_iniciais),
    ]
