# Generated by Django 5.2.4 on 2025-09-02 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='setor',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
        migrations.AddField(
            model_name='subsetor',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsetores_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
