# Generated by Django 5.2.4 on 2025-09-05 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorias', '0010_opcaopergunta_instrucoes_usuario_and_more'),
        ('organizacao', '0002_area_usuario_responsavel_empresa_usuario_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Título do Fórum')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fórum',
                'verbose_name_plural': 'Fóruns',
            },
        ),
        migrations.CreateModel(
            name='MensagemForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='planos_de_acao.forum')),
            ],
            options={
                'verbose_name': 'Mensagem de Fórum',
                'verbose_name_plural': 'Mensagens de Fórum',
                'ordering': ['data_envio'],
            },
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nao_conformidade', models.CharField(max_length=50, unique=True, verbose_name='ID Não Conformidade')),
                ('descricao_desvio', models.TextField(verbose_name='Descrição do Desvio')),
                ('acao_corretiva', models.TextField(blank=True, null=True, verbose_name='Ação Corretiva')),
                ('prazo_conclusao', models.DateField(verbose_name='Prazo de Conclusão')),
                ('perfil_responsavel', models.CharField(max_length=100, verbose_name='Perfil')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('criticidade', models.CharField(blank=True, choices=[('NC MAIOR', 'Não Conformidade Maior'), ('NC MENOR', 'Não Conformidade Menor'), ('DESVIO SOLUCIONADO', 'Desvio Solucionado'), ('NA', 'N/A')], max_length=20, null=True, verbose_name='Criticidade')),
                ('analise', models.TextField(blank=True, null=True, verbose_name='Análise')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.categoriaauditoria')),
                ('ferramenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.ferramentadigital')),
                ('ferramentas_auxiliares', models.ManyToManyField(blank=True, related_name='nao_conformidades', to='auditorias.ferramentacausaraiz', verbose_name='Ferramentas Auxiliares')),
                ('forum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planos_de_acao.forum')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorias.auditoriainstancia', verbose_name='ID do Formulário')),
                ('local_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades_area', to='organizacao.area')),
                ('local_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades_empresa', to='organizacao.empresa')),
                ('local_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades_setor', to='organizacao.setor')),
                ('local_subsetor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nao_conformidades_subsetor', to='organizacao.subsetor')),
                ('responsavel_acao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
                ('titulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorias.topico', verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
                'ordering': ['-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='ResponsavelLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.area')),
                ('local_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.empresa')),
                ('local_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.setor')),
                ('local_subsetor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.subsetor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Responsável por Local',
                'verbose_name_plural': 'Responsáveis por Local',
            },
        ),
    ]
