# Generated by Django 5.2.3 on 2025-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_de_acao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naoconformidade',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura'),
        ),
    ]
