# Generated by Django 5.2.3 on 2025-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_de_acao', '0002_alter_naoconformidade_data_abertura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagemforum',
            options={'verbose_name': 'Mensagem de Fórum'},
        ),
        migrations.AddField(
            model_name='mensagemforum',
            name='editado',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
    ]
