# Generated by Django 5.2.4 on 2025-07-25 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['descricao'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nome',
        ),
        migrations.AddField(
            model_name='turno',
            name='descricao',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Descrição do Turno'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TurnoDetalheDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Início')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Fim')),
                ('intervalo', models.DurationField(default=datetime.timedelta(0), verbose_name='Intervalo (Duração)')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros_base.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Detalhe do Turno por Dia',
                'verbose_name_plural': 'Detalhes do Turno por Dia',
                'ordering': ['dia_semana'],
                'unique_together': {('turno', 'dia_semana')},
            },
        ),
    ]
